Vagrant.configure(2) do |config|

  ap_name = "clc"
  # ap_name = "account-manager"
  # ap_name = "milkyway"
  use_db = "1" #1:利用する、0:利用しない


  config.ssh.insert_key = false

  config.vm.box = "cibt0943/centos7_ruby2.3"
  config.vm.network "private_network", ip: "192.168.99.99"
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.synced_folder "src/" + ap_name, "/var/www/rails_app", create: true, mount_options: ['dmode=755','fmode=755']
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
    vb.name = ap_name
  end

  config.vm.provision "shell", path: "scripts/provision.sh", privileged: false, args: [ap_name, use_db]
end