Vagrant.configure(2) do |config|
  ruby_version = "2.6.4"

  config.ssh.insert_key = false
  config.vbguest.no_install = true

  config.vm.box = "cibt0943/centos7"
  config.vm.box_version = "0.6.0 "
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "2048"
    vb.name = "centos7_ruby" + ruby_version
  end

  config.vm.provision "shell", path: "scripts/provision.sh", privileged: true, args: [ruby_version]
  config.vm.provision "shell", path: "scripts/cleanup.sh", privileged: true
end
