Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vbguest.no_install = true

  config.vm.box = "cibt0943/centos7"
  config.vm.box_version = "7.9.2009.20210323"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
    vb.name = "centos7_mysql5.6"
  end

  config.vm.provision "shell", path: "scripts/provision.sh", privileged: true
  config.vm.provision "shell", path: "scripts/cleanup.sh", privileged: true
end