Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
    vb.name = "centos7"
  end

  config.vm.provision "shell", path: "scripts/provision.sh", privileged: true
  config.vm.provision "shell", path: "scripts/cleanup.sh", privileged: true
end